export default [
  {
    id: 1,
    type: 'R2-D2',
    image: '/images/droids/r2-d2.png',
    status: 'Pending',
    partsNeeded: ['Motivator', 'Power Coupling'],
  },
  {
    id: 2,
    type: 'BB-8',
    image: '/images/droids/bb-8.png',
    status: 'Pending',
    partsNeeded: ['Arc Welder', 'Power Coupling'],
  },
  {
    id: 3,
    type: 'C-3PO',
    image: '/images/droids/c-3po.png',
    status: 'Pending',
    partsNeeded: ['Translation Module', 'Power Coupling'],
  },
  {
    id: 4,
    type: 'K-2SO',
    image: '/images/droids/k-2s0.png',
    status: 'Pending',
    partsNeeded: ['Arm Actuator', 'Visual Sensors'],
  },
  {
    id: 5,
    type: 'IG-88',
    status: 'Pending',
    partsNeeded: ['Weapon Module', 'Logic Board'],
  },
  {
    id: 6,
    type: 'C1-10P',
    status: 'Pending',
    partsNeeded: ['Propulsion Engine', 'Arm Actuator'],
  },
  {
    id: 7,
    type: 'Droideka',
    status: 'Pending',
    partsNeeded: ['Shield Generator', 'Laser Cannons'],
  },
  {
    id: 8,
    type: 'MSE-6',
    status: 'Pending',
    partsNeeded: ['Wheels', 'Audio Receiver'],
  },
  {
    id: 9,
    type: 'Battle Droid',
    status: 'Pending',
    partsNeeded: ['Leg Assembly', 'Laser Cannons'],
  },
  {
    id: 10,
    type: 'Probe Droid',
    status: 'Pending',
    partsNeeded: ['Visual Sensors', 'Antenna'],
  },
  {
    id: 11,
    type: 'L3-37',
    status: 'Pending',
    partsNeeded: ['Memory Bank', 'Leg Assembly'],
  },
  {
    id: 12,
    type: 'R4-P17',
    status: 'Pending',
    partsNeeded: ['Dome Panel', 'Power Coupling'],
  },
  {
    id: 13,
    type: 'R5-D4',
    image:
      'https://static.wikia.nocookie.net/starwars/images/droids/3/3f/R5D4-AG.png/revision/latest?cb=20230317020800',
    status: 'Pending',
    partsNeeded: ['Power Core', 'Motivator'],
  },
  {
    id: 14,
    type: 'T3-M4',
    image:
      'https://static.wikia.nocookie.net/starwars/images/droids/f/fb/T3-M4-promo.jpg/revision/latest?cb=20100121131618',
    status: 'Pending',
    partsNeeded: ['Logic Board', 'Interface Adapter'],
  },
  {
    id: 15,
    type: 'Medical Droid',
    status: 'Pending',
    partsNeeded: ['Surgical Tools', 'Manipulator Arm'],
  },
  {
    id: 16,
    type: 'Astromech Droid',
    status: 'Pending',
    partsNeeded: ['Navigation Computer', 'Thrusters'],
  },
  {
    id: 17,
    type: 'Pit Droid',
    status: 'Pending',
    partsNeeded: ['Mechanical Arms', 'Hydraulic System'],
  },
  {
    id: 18,
    type: 'BX-Series Droid Commando',
    status: 'Pending',
    partsNeeded: ['Camouflage Netting', 'Weapon Module'],
  },
  {
    id: 19,
    type: 'Magnaguard',
    status: 'Pending',
    partsNeeded: ['Electrostaff', 'Combat Programming'],
  },
  {
    id: 20,
    type: 'HK-47',
    status: 'Pending',
    partsNeeded: ['Vocal Processor', 'Assassination Protocols'],
  },
];
